# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    env_file: 
      - ".env.example"
      - ".env"
    environment:
      DB_HOST: db
      RUNNING_IN_DOCKER: 1
    restart: unless-stopped
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy


  db:
      image: mysql:lts
      env_file: 
      - ".env.example"
      - ".env"
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB}
      restart: unless-stopped
      ports:
        - "3306:3306"
      volumes:
        - db-data:/var/lib/mysql
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p-p${DB_PASSWORD}"]
        interval: 5s
        retries: 10

networks:
  default:
    ipam:
      config:
        - subnet: 10.200.0.0/24


volumes:
  db-data: {}
